services:
  clash-gen:
    image: ghcr.io/10000ge10000/clash-config-gen:main
    container_name: clash-gen
    restart: always
    ports:
      - "${WEB_PORT:-8501}:8501"
      - "${API_PORT:-8000}:8000"
    environment:
      - PUBLIC_BASE_URL=${PUBLIC_BASE_URL}
      - APP_DB_PATH=/app/data/app.db
      - ALLOW_REGISTRATION=${ALLOW_REGISTRATION:-false}
      - AUTH_COOKIE_SECURE=${AUTH_COOKIE_SECURE:-true}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - RULESET_CACHE_ENABLED=${RULESET_CACHE_ENABLED:-true}
      - RULESET_UPDATE_INTERVAL=${RULESET_UPDATE_INTERVAL:-604800}
      - RULESET_CACHE_DIR=/app/ruleset/dustinwin
    volumes:
      - ./data:/app/data
      - ./ruleset:/app/ruleset
